# Generated by Django 5.2.7 on 2025-11-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_producto_codigo_barra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barra',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo promedio o actual del producto para análisis de rentabilidad', max_digits=10, null=True),
        ),
    ]
