# Generated by Django 5.2.7 on 2025-11-27 17:25

from django.db import migrations


def add_costo_unitario_column(apps, schema_editor):
    """Add costo_unitario column if it doesn't exist"""
    with schema_editor.connection.cursor() as cursor:
        # Check if column exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'pos_producto' 
            AND COLUMN_NAME = 'costo_unitario'
        """)
        column_exists = cursor.fetchone()[0] > 0
        
        if not column_exists:
            # Add the column
            cursor.execute("""
                ALTER TABLE pos_producto 
                ADD COLUMN costo_unitario DECIMAL(10, 2) NULL 
                COMMENT 'Costo promedio o actual del producto para análisis de rentabilidad'
            """)
            print("✓ Added costo_unitario column to pos_producto")
        else:
            print("✓ costo_unitario column already exists")


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_alter_producto_codigo_barra_and_more'),
    ]

    operations = [
        migrations.RunPython(add_costo_unitario_column, migrations.RunPython.noop),
    ]
