# Generated by Django 5.2.8 on 2025-12-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_alter_empleado_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_referencial',
            field=models.ImageField(blank=True, help_text='Imagen principal de referencia del producto.', null=True, upload_to='productos_imagenes/'),
        ),
    ]
