# Generated by Django 5.2.8 on 2025-12-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_producto_imagen_referencial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='monto_recibido',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto total entregado por el cliente (solo en efectivo).', max_digits=10),
        ),
        migrations.AddField(
            model_name='pago',
            name='vuelto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Vuelto entregado al cliente (solo en efectivo).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text='Monto APLICADO a la venta.', max_digits=10),
        ),
    ]
