# Generated by Django 5.2.7 on 2025-12-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_pago_monto_recibido_pago_vuelto_alter_pago_monto'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_gasto', models.CharField(choices=[('alquiler', 'Alquiler'), ('servicios', 'Servicios (luz, agua, gas)'), ('salarios', 'Salarios'), ('marketing', 'Marketing y Publicidad'), ('mantenimiento', 'Mantenimiento'), ('suministros', 'Suministros'), ('transporte', 'Transporte'), ('impuestos', 'Impuestos y Licencias'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('es_recurrente', models.BooleanField(default=False, help_text='Si es un gasto mensual fijo')),
            ],
            options={
                'verbose_name': 'Gasto Operativo',
                'verbose_name_plural': 'Gastos Operativos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.RemoveField(
            model_name='ordencompraitem',
            name='insumo',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='ordencompraitem',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='monto_recibido',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='vuelto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen_referencial',
        ),
        migrations.AddField(
            model_name='empleado',
            name='apellido_paterno',
            field=models.CharField(default='Sin apellido', max_length=45),
        ),
        migrations.AddField(
            model_name='empleado',
            name='clave',
            field=models.CharField(default='cambiar123', max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='correo',
            field=models.EmailField(default='sin@correo.com', max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombres',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo promedio o actual del producto para análisis de rentabilidad', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(default='Empleado', max_length=45),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=200),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fono',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='run',
            field=models.CharField(default='00000000-0', max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='precio_costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo de compra neto', max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada (Compra)'), ('salida', 'Salida (Venta)'), ('merma', 'Merma/Ajuste')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora_salida',
            field=models.TimeField(),
        ),
        migrations.DeleteModel(
            name='Insumo',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='OrdenCompra',
        ),
        migrations.DeleteModel(
            name='OrdenCompraItem',
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
    ]
