# Generated by Django 5.2.7 on 2025-12-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_gastooperativo_remove_ordencompraitem_insumo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
