# Generated by Django 5.2.8 on 2025-12-13 16:42

import pos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_gastooperativo_producto_costo_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_referencial',
            field=models.ImageField(blank=True, null=True, upload_to=pos.models.renombrar_imagen),
        ),
    ]
