# Generated by Django 5.2.8 on 2025-12-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_alter_producto_imagen_referencial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
