# Generated by Django 5.2.8 on 2025-12-15 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_etiqueta_alter_lote_precio_costo_unitario_and_more'),
        ('pos', '0010_venta_fecha_entrega'),
    ]

    operations = [
    ]
