# Generated by Django 5.2.8 on 2025-12-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_merge_20251215_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen_referencial',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL de la imagen en Cloudinary', max_length=500, null=True),
        ),
    ]
